export const RESET = 'RESET';
// export const INIT = 'INIT';
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const START = 'START';
export const CORRECT = 'CORRECT';
export const WRONG = 'WRONG';
export const WIN = 'WIN'; 
export const COMPLETE = 'COMPLETE'; 
export const SET_MULTIPLAYER = 'SET_MULTIPLAYER'; 
